Repository oceanbase/oblogclient, pull requests merged in 2021-12, with the labels that each got.

#9 update handle for join interrupted
  logproxy-client/src/main/java/com/oceanbase/clogproxy/client/connection/ClientStream.java
Labels: enhancement

#11 upgrade and make logmessage as a single package
  common/pom.xml
  common/src/main/java/com/oceanbase/oms/logmessage/ByteString.java
  common/src/main/java/com/oceanbase/oms/logmessage/Checkpoint.java
  common/src/main/java/com/oceanbase/oms/logmessage/DataMessage.java
  common/src/main/java/com/oceanbase/oms/logmessage/FieldParseListener.java
  common/src/main/java/com/oceanbase/oms/logmessage/LogMessage.java
  common/src/main/java/com/oceanbase/oms/logmessage/LogMessageException.java
  common/src/main/java/com/oceanbase/oms/logmessage/Message.java
  common/src/main/java/com/oceanbase/oms/logmessage/enums/DBType.java
  common/src/main/java/com/oceanbase/oms/logmessage/enums/DataType.java
  common/src/main/java/com/oceanbase/oms/logmessage/typehelper/LogMessageTypeCode.java
  common/src/main/java/com/oceanbase/oms/logmessage/typehelper/LogTypeHelper.java
  common/src/main/java/com/oceanbase/oms/logmessage/typehelper/LogTypeHelperFactory.java
  common/src/main/java/com/oceanbase/oms/logmessage/typehelper/OBLogTypeHelper.java
  common/src/main/java/com/oceanbase/oms/logmessage/utils/BinaryMessageUtils.java
  common/src/main/java/com/oceanbase/oms/logmessage/utils/StringUtils.java
  logproxy-client/src/main/java/com/oceanbase/clogproxy/client/connection/ClientHandler.java
  logproxy-client/src/main/java/com/oceanbase/clogproxy/client/connection/StreamContext.java
  logproxy-client/src/main/java/com/oceanbase/clogproxy/client/listener/RecordListener.java
  logproxy-client/src/test/java/com/oceanbase/clogproxy/client/LogProxyClientTest.java
Labels: breaking change, refactor

#17 update logback to version 1.2.10
  pom.xml
Labels: dependencies

#18 [doc] update usage and add logmessage document
  README.md
  common/src/main/java/com/oceanbase/oms/logmessage/DataMessage.java
  docs/formats/logmessage.md
  docs/quickstart/logproxy-client-tutorial.md
Labels: documentation

#19 add workflow desc in logproxy-client-tutorial.md
  .gitattributes
  docs/images/logproxy-client-workflow.png
  docs/quickstart/logproxy-client-tutorial.md
Labels: documentation

#20 add developers info & remove gpg plugin
  pom.xml
Labels: compile
